#!/bin/sh

mkdir -p /Library/Palourde/Definitions
su $USER -c '/Library/Palourde/Palourde.app/Contents/MacOS/Palourde -panel &'
sleep 10
cd /tmp && /Library/Palourde/Palourde.app/Contents/Resources/bin/freshclam
launchctl load -w /Library/LaunchDaemons/net.palourde.clamd.plist
launchctl load -w /Library/LaunchDaemons/net.palourde.freshclam.plist
su $USER -c  'launchctl load -w /Library/LaunchAgents/net.palourde.agent.plist'
#launchctl start com.macbouffon.palourde.clamd
#launchctl start com.macbouffon.palourde.agent